namespace SharePointLinkManifestBuilder.Core.Models;

/// <summary>What kind of drive item was found.</summary>
public enum DriveItemKind
{
    /// <summary>An ordinary file.</summary>
    File = 0,

    /// <summary>A folder.</summary>
    Folder = 1,

    /// <summary>A package such as a OneNote notebook, which behaves as a unit, not a file.</summary>
    Package = 2,

    /// <summary>A shortcut or remote item pointing elsewhere.</summary>
    RemoteItem = 3,

    /// <summary>An item Graph returned that this application does not know how to classify.</summary>
    Unsupported = 4,
}

/// <summary>Why a discovered item will not have a link created for it.</summary>
public enum SkipReason
{
    /// <summary>Not skipped.</summary>
    None = 0,

    /// <summary>The item is a folder and the job creates links for files only.</summary>
    IsFolder,

    /// <summary>An Office lock or temporary file, for example one beginning with "~$".</summary>
    TemporaryFile,

    /// <summary>A manifest this application generates, excluded so a job never ingests its own output.</summary>
    GeneratedManifest,

    /// <summary>Marked hidden or as a system artifact.</summary>
    HiddenOrSystem,

    /// <summary>A OneNote notebook or other package that is not a single shareable file.</summary>
    PackageItem,

    /// <summary>A shortcut or remote item whose real location is elsewhere.</summary>
    RemoteItem,

    /// <summary>Excluded by the configured extension, pattern, date, or size filters.</summary>
    FilteredOut,

    /// <summary>Already processed through another overlapping target in the same job.</summary>
    DuplicateAcrossTargets,

    /// <summary>Graph returned an item type this application cannot share.</summary>
    UnsupportedItemType,
}

/// <summary>
/// A file found during enumeration. Identity is (<see cref="DriveId"/>, <see cref="ItemId"/>)
/// and never the name or path; see docs/adr/0007-file-identity-drive-item.md.
/// </summary>
public sealed record DiscoveredFile
{
    /// <summary>Drive containing the item.</summary>
    public required string DriveId { get; init; }

    /// <summary>Graph item ID. Together with the drive ID this is the file's identity.</summary>
    public required string ItemId { get; init; }

    /// <summary>File name including extension.</summary>
    public required string Name { get; init; }

    /// <summary>Path relative to the target's starting folder, forward-slashed.</summary>
    public string RelativePath { get; init; } = string.Empty;

    /// <summary>Absolute URL of the item in SharePoint or OneDrive.</summary>
    public string? WebUrl { get; init; }

    /// <summary>Size in bytes, when Graph reports it.</summary>
    public long? Size { get; init; }

    /// <summary>Last modification timestamp, when Graph reports it.</summary>
    public DateTimeOffset? LastModifiedUtc { get; init; }

    /// <summary>Item ETag, used for change detection.</summary>
    public string? ETag { get; init; }

    /// <summary>Item ID of the containing folder, used to group per-folder manifests.</summary>
    public string? ParentFolderItemId { get; init; }

    /// <summary>Path of the containing folder relative to the target start, forward-slashed.</summary>
    public string ParentRelativePath { get; init; } = string.Empty;

    /// <summary>Classification of the item.</summary>
    public DriveItemKind Kind { get; init; } = DriveItemKind.File;

    /// <summary>Why the item will be skipped, if it will be.</summary>
    public SkipReason SkipReason { get; init; } = SkipReason.None;

    /// <summary>The target this item was discovered through.</summary>
    public string? TargetId { get; init; }

    /// <summary>True when this file will have a sharing link requested for it.</summary>
    public bool IsEligible => SkipReason == SkipReason.None && Kind == DriveItemKind.File;

    /// <summary>The identity key used for deduplication and manifest matching.</summary>
    public string IdentityKey => $"{DriveId}|{ItemId}";

    /// <summary>A human-readable reason a file is skipped, for the preview and report.</summary>
    public string SkipExplanation => SkipReason switch
    {
        SkipReason.None => string.Empty,
        SkipReason.IsFolder => "Folders are not shared; only files receive links.",
        SkipReason.TemporaryFile => "Temporary or lock file.",
        SkipReason.GeneratedManifest => "A manifest generated by this application.",
        SkipReason.HiddenOrSystem => "Marked hidden or as a system artifact.",
        SkipReason.PackageItem => "A package such as a OneNote notebook, not a single shareable file.",
        SkipReason.RemoteItem => "A shortcut or remote item stored in another location.",
        SkipReason.FilteredOut => "Excluded by the configured filters.",
        SkipReason.DuplicateAcrossTargets => "Already processed through another selected target.",
        SkipReason.UnsupportedItemType => "Microsoft Graph returned an item type that cannot be shared.",
        _ => "Skipped.",
    };
}
