namespace SharePointLinkManifestBuilder.Core.Models;

/// <summary>
/// Optional rules narrowing which discovered files are eligible. All rules are conjunctive:
/// a file must satisfy every configured rule to be included.
/// </summary>
public sealed record FilterConfiguration
{
    /// <summary>
    /// Extensions to include, with or without a leading dot. Empty means all extensions.
    /// </summary>
    public IReadOnlyList<string> IncludeExtensions { get; init; } = [];

    /// <summary>Extensions to exclude, applied after <see cref="IncludeExtensions"/>.</summary>
    public IReadOnlyList<string> ExcludeExtensions { get; init; } = [];

    /// <summary>Glob patterns a file name must match. Empty means no name restriction.</summary>
    public IReadOnlyList<string> IncludePatterns { get; init; } = [];

    /// <summary>Glob patterns that exclude a file name.</summary>
    public IReadOnlyList<string> ExcludePatterns { get; init; } = [];

    /// <summary>Only include files modified at or after this instant.</summary>
    public DateTimeOffset? ModifiedAfterUtc { get; init; }

    /// <summary>Only include files modified at or before this instant.</summary>
    public DateTimeOffset? ModifiedBeforeUtc { get; init; }

    /// <summary>Minimum size in bytes, inclusive.</summary>
    public long? MinimumSizeBytes { get; init; }

    /// <summary>Maximum size in bytes, inclusive.</summary>
    public long? MaximumSizeBytes { get; init; }

    /// <summary>Include items Graph marks hidden or system. Off by default.</summary>
    public bool IncludeHiddenAndSystemItems { get; init; }

    /// <summary>Include Office lock and temporary files such as "~$report.docx". Off by default.</summary>
    public bool IncludeTemporaryFiles { get; init; }

    /// <summary>
    /// Include manifests generated by this application. Off by default so a job never
    /// discovers and re-processes its own output.
    /// </summary>
    public bool IncludeGeneratedManifests { get; init; }

    /// <summary>
    /// Include packages such as OneNote notebooks and remote/shortcut items. Off by default;
    /// these are not single shareable files and behave unpredictably.
    /// </summary>
    public bool IncludeSpecialItemTypes { get; init; }

    /// <summary>True when no rule has been configured and every file passes.</summary>
    public bool IsEmpty =>
        IncludeExtensions.Count == 0 && ExcludeExtensions.Count == 0
        && IncludePatterns.Count == 0 && ExcludePatterns.Count == 0
        && ModifiedAfterUtc is null && ModifiedBeforeUtc is null
        && MinimumSizeBytes is null && MaximumSizeBytes is null
        && !IncludeHiddenAndSystemItems && !IncludeTemporaryFiles
        && !IncludeGeneratedManifests && !IncludeSpecialItemTypes;

    /// <summary>A readable summary of the active rules, shown before a job runs.</summary>
    public string Describe()
    {
        if (IsEmpty)
        {
            return "All files (default exclusions apply: temporary files, generated manifests, "
                + "hidden and system items, packages and shortcuts).";
        }

        var parts = new List<string>();

        if (IncludeExtensions.Count > 0)
        {
            parts.Add($"only {string.Join(", ", IncludeExtensions)}");
        }

        if (ExcludeExtensions.Count > 0)
        {
            parts.Add($"excluding {string.Join(", ", ExcludeExtensions)}");
        }

        if (IncludePatterns.Count > 0)
        {
            parts.Add($"matching {string.Join(", ", IncludePatterns)}");
        }

        if (ExcludePatterns.Count > 0)
        {
            parts.Add($"not matching {string.Join(", ", ExcludePatterns)}");
        }

        if (ModifiedAfterUtc.HasValue)
        {
            parts.Add($"modified on or after {ModifiedAfterUtc.Value.UtcDateTime:yyyy-MM-dd}");
        }

        if (ModifiedBeforeUtc.HasValue)
        {
            parts.Add($"modified on or before {ModifiedBeforeUtc.Value.UtcDateTime:yyyy-MM-dd}");
        }

        if (MinimumSizeBytes.HasValue)
        {
            parts.Add($"at least {FormatBytes(MinimumSizeBytes.Value)}");
        }

        if (MaximumSizeBytes.HasValue)
        {
            parts.Add($"at most {FormatBytes(MaximumSizeBytes.Value)}");
        }

        if (IncludeHiddenAndSystemItems)
        {
            parts.Add("including hidden and system items");
        }

        if (IncludeTemporaryFiles)
        {
            parts.Add("including temporary files");
        }

        if (IncludeGeneratedManifests)
        {
            parts.Add("including generated manifests");
        }

        if (IncludeSpecialItemTypes)
        {
            parts.Add("including packages and shortcuts");
        }

        return string.Join("; ", parts);
    }

    /// <summary>Validates the rules, returning one message per problem.</summary>
    public IReadOnlyList<string> Validate()
    {
        var problems = new List<string>();

        if (ModifiedAfterUtc.HasValue && ModifiedBeforeUtc.HasValue
            && ModifiedAfterUtc > ModifiedBeforeUtc)
        {
            problems.Add("The 'modified after' date is later than the 'modified before' date, so nothing can match.");
        }

        if (MinimumSizeBytes.HasValue && MaximumSizeBytes.HasValue
            && MinimumSizeBytes > MaximumSizeBytes)
        {
            problems.Add("The minimum size is larger than the maximum size, so nothing can match.");
        }

        if (MinimumSizeBytes is < 0 || MaximumSizeBytes is < 0)
        {
            problems.Add("File sizes cannot be negative.");
        }

        return problems;
    }

    private static string FormatBytes(long bytes) => bytes switch
    {
        >= 1024L * 1024 * 1024 => $"{bytes / (1024.0 * 1024 * 1024):0.##} GB",
        >= 1024 * 1024 => $"{bytes / (1024.0 * 1024):0.##} MB",
        >= 1024 => $"{bytes / 1024.0:0.##} KB",
        _ => $"{bytes} bytes",
    };
}
